"use client";
import { useEffect, useState } from 'react';
import { Panel } from '@/components/primitives/panel';
import { PERFORMANCE_METRICS, MEMBERSHIP_GOAL_METRICS, TECHNICIAN_GOAL_METRICS, goalInputToCanonical, formatPerformanceGoal, type PerformanceMetric, type PerformanceTargetRow } from '@/lib/performance-goals';
interface Roster { roles: Array<{code:string;name:string}>; employees: Array<{id:number;name:string}> }
const inputClass='w-full rounded border border-border bg-surface-2 p-3 text-[13px]';
async function request(url:string,init?:RequestInit) { const r=await fetch(url,init); const j=await r.json();if(!r.ok)throw new Error(j.error??`HTTP ${r.status}`);return j; }
export function PerformanceGoalsEditor({mode}:{mode:'membership'|'technician'}) {
 const metrics=mode==='membership'?MEMBERSHIP_GOAL_METRICS:TECHNICIAN_GOAL_METRICS;
 const [rows,setRows]=useState<PerformanceTargetRow[]>([]),[roster,setRoster]=useState<Roster>({roles:[],employees:[]}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[message,setMessage]=useState('');
 const [id,setId]=useState<number|undefined>(),[metric,setMetric]=useState<PerformanceMetric>(metrics[0]),[scope,setScope]=useState(mode==='membership'?'company':'role'),[scopeValue,setScopeValue]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[value,setValue]=useState('');
 async function load(){const [t,r]=await Promise.all([request('/api/admin/performance-goals'),request('/api/admin/performance-roster')]);setRows(t.rows);setRoster(r);setReady(true);}
 useEffect(()=>{load().catch(e=>setError(String(e.message)));},[]);
 function reset(){setId(undefined);setValue('');setMessage('');}
 async function save(e:React.FormEvent){e.preventDefault();setError('');setMessage('');const canonical=goalInputToCanonical(value,PERFORMANCE_METRICS[metric].unit);if(canonical==null){setError('Enter a nonnegative value. Dollars and percentages allow two decimal places; counts must be whole numbers.');return;}setBusy(true);try{await request('/api/admin/performance-goals',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,metric,scope,scopeValue:scope==='company'?null:scopeValue,effectiveFrom:from,effectiveTo:to,targetValue:canonical,unit:PERFORMANCE_METRICS[metric].unit})});await load();reset();setMessage('Goal saved. The dashboard uses this company’s saved goals.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function edit(r:PerformanceTargetRow){setId(r.id);setMetric(r.metric as PerformanceMetric);setScope(r.scope);setScopeValue(r.scopeValue??'');setFrom(r.effectiveFrom);setTo(r.effectiveTo);setValue(String(r.targetValue/(r.unit==='count'?1:100)));setMessage('');setError('');}
 async function remove(r:PerformanceTargetRow){if(!window.confirm('Delete this goal? The dashboard will use any applicable role default, or show Not set.'))return;setBusy(true);setError('');try{await request(`/api/admin/performance-goals?id=${r.id}&scope=${r.scope}`,{method:'DELETE'});await load();if(id===r.id)reset();setMessage('Goal deleted.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const visible=rows.filter(r=>metrics.includes(r.metric as PerformanceMetric)&&(mode==='membership'?r.scope==='company':['role','employee'].includes(r.scope)));
 const scopeName=(r:PerformanceTargetRow)=>r.scope==='company'?'Company-wide':r.scope==='role'?`Role default: ${roster.roles.find(x=>x.code===r.scopeValue)?.name??r.scopeValue}`:`Individual override: ${roster.employees.find(x=>String(x.id)===r.scopeValue)?.name??r.scopeValue}`;
 return <div className="flex flex-col gap-6"><Panel title={mode==='membership'?'Membership Goals':'Technician Targets'}><p className="text-[13px] text-muted leading-relaxed">{mode==='membership'?'Set separate targets for active membership inventory and membership starts. Active inventory is a point-in-time goal; starts are a flow over the effective date range.':'Set role-level defaults and individual technician overrides. Overrides take priority. Sales goals use ServiceTitan TotalSales, not invoice Revenue. Flow goals are prorated by calendar days; close-rate and average-ticket goals are not prorated.'} All values belong to this company only. Domo revenue budgets are not changed. Technician choices include synced reports, excluding known inactive roster entries.</p></Panel>
 <Panel title={id?'Edit goal':'Add goal'}><form onSubmit={save} className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4"><label className="text-[12px]">Metric<select className={inputClass} value={metric} onChange={e=>{setMetric(e.target.value as PerformanceMetric);reset();}}>{metrics.map(m=><option value={m} key={m}>{PERFORMANCE_METRICS[m].label}</option>)}</select></label>{mode==='technician'&&<><label className="text-[12px]">Scope<select className={inputClass} value={scope} onChange={e=>{setScope(e.target.value);setScopeValue('');setId(undefined);}}><option value="role">Role default</option><option value="employee">Individual override</option></select></label><label className="text-[12px]">{scope==='role'?'Role':'Technician'}<select className={inputClass} required value={scopeValue} onChange={e=>setScopeValue(e.target.value)}><option value="">Select...</option>{scope==='role'?roster.roles.map(r=><option key={r.code} value={r.code}>{r.name}</option>):roster.employees.map(r=><option key={r.id} value={r.id}>{r.name} (ST {r.id})</option>)}</select></label></>}
 <label className="text-[12px]">Effective from<input type="date" className={inputClass} required value={from} onChange={e=>setFrom(e.target.value)} /></label><label className="text-[12px]">Effective through<input type="date" className={inputClass} required min={from||undefined} value={to} onChange={e=>setTo(e.target.value)} /></label><label className="text-[12px]">Goal ({PERFORMANCE_METRICS[metric].unit==='cents'?'dollars':PERFORMANCE_METRICS[metric].unit==='bps'?'percent':'count'})<input className={inputClass} inputMode="decimal" required value={value} onChange={e=>setValue(e.target.value)} placeholder="Not set" /></label><div className="flex gap-3 items-center"><button className="rounded bg-accent text-bg px-4 py-3 font-semibold disabled:opacity-40" disabled={busy||!ready} type="submit">{busy?'Saving...':id?'Save changes':'Save goal'}</button>{id&&<button type="button" className="p-3 border border-border rounded" onClick={reset} disabled={busy}>Cancel edit</button>}</div></form>{error&&<p role="alert" className="text-down mt-4">{error}</p>}{message&&<p role="status" className="text-up mt-4">{message}</p>}</Panel>
 <Panel title="Saved goals"><div className="flex flex-col divide-y divide-border">{visible.map(r=><div className="flex flex-wrap justify-between items-center gap-3 py-4" key={r.id}><div><div className="font-medium text-[13px]">{PERFORMANCE_METRICS[r.metric as PerformanceMetric].label}</div><div className="text-[12px] text-muted mt-1">{scopeName(r)} · {r.effectiveFrom} through {r.effectiveTo}</div><div className="font-mono mt-2">{formatPerformanceGoal(r.targetValue,r.unit)}</div></div><div className="flex gap-3"><button disabled={busy} className="border border-border rounded px-4 py-2" onClick={()=>edit(r)}>Edit</button><button disabled={busy} className="border border-border rounded px-4 py-2 text-down" onClick={()=>remove(r)}>Delete</button></div></div>)}{ready&&visible.length===0&&<p className="text-muted py-4">No goals set. The dashboard shows Not set until a goal is saved.</p>}</div></Panel></div>;
}
