"use client";
import { useQuery } from '@tanstack/react-query';
import type { ApiEnvelope, MembershipsResponse } from '@/lib/types/kpi';
import { TvHeader } from './tv-header';
const n=(v:number|null|undefined)=>v==null?'Unavailable':v.toLocaleString();
export function MembershipsScene() {
 const {data,error}=useQuery<MembershipsResponse>({queryKey:['tv-memberships','mtd'],queryFn:async()=>{const r=await fetch('/api/kpi/memberships?preset=mtd');if(!r.ok)throw new Error(`memberships: ${r.status}`);return ((await r.json()) as ApiEnvelope<MembershipsResponse>).data;},staleTime:60_000,refetchInterval:300_000});
 if(!data)return <TvHeader eyebrow="Memberships" title={error?'Membership data unavailable':'Loading...'} />;
 return <div className="flex flex-col gap-6 h-full"><TvHeader eyebrow="Memberships" title="Membership health" right={`Snapshot: ${data.meta.snapshotDate??'Unavailable'}`} /><div className="grid grid-cols-2 gap-8"><div><p className="text-muted">Active memberships</p><div className="text-display font-mono" style={{fontSize:'clamp(72px, 10vw, 160px)'}}>{n(data.active)}</div><p className="text-muted">Active goal: {data.goal==null?'Not set':n(data.goal)}</p></div><div><p className="text-muted">End date in less than 30 days</p><div className="text-display font-mono">{n(data.health?.expiringUnder30)}</div><p className="text-muted">Follow-up signal, not confirmed churn</p></div></div><div className="grid grid-cols-4 gap-4">{[['Starts MTD',data.newMonth],['Cancellations MTD',data.churnMonth],['Expirations MTD',data.expirations],['Net activity',data.netMonth]].map(([label,value])=><div className="rounded-panel border border-border p-4" key={String(label)}><div className="text-muted text-eyebrow">{label}</div><div className="text-[32px] font-mono">{n(value as number|null)}</div></div>)}</div><div className="grid grid-cols-2 gap-3 overflow-auto">{data.breakdown.filter(p=>p.count>0).map(p=><div className="rounded-panel border border-border p-4 flex justify-between gap-4" key={p.tier}><span>{p.tier}</span><span className="font-mono text-[24px]">{n(p.count)}</span></div>)}</div></div>;
}
